<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="3b7b2133aad05b1" failures="2" tests="10" name="SCMS_Business_Logic_Validation" time="0.871" errors="0" timestamp="2025-09-30T20:30:50 IST">
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.681">
    <failure type="com.company.scm.exception.EntityNotFoundException" message="W001">
      <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:601)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="@AfterMethod cleanup" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testAddStockSuccess" time="0.0">
    <skipped/>
  </testcase> <!-- testAddStockSuccess -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testAddStock_ZeroQuantity_ThrowsException" time="0.0">
    <skipped/>
  </testcase> <!-- testAddStock_ZeroQuantity_ThrowsException -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testRemoveStockExceedingQuantity_ThrowsException" time="0.001">
    <skipped/>
  </testcase> <!-- testRemoveStockExceedingQuantity_ThrowsException -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testRemoveStockSuccess" time="0.0">
    <skipped/>
  </testcase> <!-- testRemoveStockSuccess -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testStockTransferUpdatesBothWarehouses" time="0.0">
    <skipped/>
  </testcase> <!-- testStockTransferUpdatesBothWarehouses -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testStockTransferUpdatesBothWarehouses" time="0.0">
    <skipped/>
  </testcase> <!-- testStockTransferUpdatesBothWarehouses -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testStockTransferUpdatesBothWarehouses" time="0.001">
    <skipped/>
  </testcase> <!-- testStockTransferUpdatesBothWarehouses -->
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testTransferStock_InvalidDestination_ThrowsException" time="0.0">
    <skipped/>
  </testcase> <!-- testTransferStock_InvalidDestination_ThrowsException -->
  <testcase classname="com.company.scm.service.OrderServiceTest" name="testFulfillSalesOrder_Success" time="0.041">
    <failure type="com.company.scm.exception.EntityNotFoundException" message="Inventory item for product P001 in warehouse W001 not found.">
      <![CDATA[com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.
at com.company.scm.service.InventoryService.removeStock(InventoryService.java:61)
at com.company.scm.service.OrderService.fulfillSalesOrder(OrderService.java:70)
at com.company.scm.service.OrderServiceTest.testFulfillSalesOrder_Success(OrderServiceTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- testFulfillSalesOrder_Success -->
  <testcase classname="com.company.scm.service.OrderServiceTest" name="testFulfillSalesOrder_InsufficientStock_ThrowsException" time="0.002">
    <failure type="org.testng.TestException" message="
Expected exception of type class com.company.scm.exception.InsufficientStockException but got com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.">
      <![CDATA[org.testng.TestException: 
Expected exception of type class com.company.scm.exception.InsufficientStockException but got com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.
at org.testng.internal.invokers.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:67)
at org.testng.internal.invokers.TestInvoker.considerExceptionsInternal(TestInvoker.java:888)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:863)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:742)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.
at com.company.scm.service.InventoryService.removeStock(InventoryService.java:61)
at com.company.scm.service.OrderService.fulfillSalesOrder(OrderService.java:70)
at com.company.scm.service.OrderServiceTest.testFulfillSalesOrder_InsufficientStock_ThrowsException(OrderServiceTest.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
... 16 more
]]>
    </failure>
  </testcase> <!-- testFulfillSalesOrder_InsufficientStock_ThrowsException -->
  <testcase classname="com.company.scm.service.ReportServiceTest" name="testPrintInventoryReport" time="0.0">
    <ignored/>
  </testcase> <!-- testPrintInventoryReport -->
  <testcase classname="com.company.scm.service.ReportServiceTest" name="testPrintLowStockReport" time="0.0">
    <ignored/>
  </testcase> <!-- testPrintLowStockReport -->
</testsuite> <!-- SCMS_Business_Logic_Validation -->
