<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="15" passed="3" failed="4" skipped="8">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-30T20:33:43 IST" name="Surefire suite" finished-at="2025-09-30T20:33:44 IST" duration-ms="802">
    <groups>
      <group name="report">
        <method signature="ReportServiceTest.testPrintInventoryReport()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" name="testPrintInventoryReport" class="com.company.scm.service.ReportServiceTest"/>
        <method signature="ReportServiceTest.testPrintLowStockReport()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" name="testPrintLowStockReport" class="com.company.scm.service.ReportServiceTest"/>
      </group> <!-- report -->
      <group name="orders">
        <method signature="OrderServiceTest.testFulfillSalesOrder_InsufficientStock_ThrowsException()[pri:2, instance:com.company.scm.service.OrderServiceTest@18a70f16]" name="testFulfillSalesOrder_InsufficientStock_ThrowsException" class="com.company.scm.service.OrderServiceTest"/>
        <method signature="OrderServiceTest.testFulfillSalesOrder_Success()[pri:1, instance:com.company.scm.service.OrderServiceTest@18a70f16]" name="testFulfillSalesOrder_Success" class="com.company.scm.service.OrderServiceTest"/>
      </group> <!-- orders -->
      <group name="repository">
        <method signature="ProductRepositoryTest.testFindAll()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" name="testFindAll" class="com.company.scm.repository.ProductRepositoryTest"/>
        <method signature="ProductRepositoryTest.testFindById_NotFound()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" name="testFindById_NotFound" class="com.company.scm.repository.ProductRepositoryTest"/>
        <method signature="ProductRepositoryTest.testFindById_Success()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" name="testFindById_Success" class="com.company.scm.repository.ProductRepositoryTest"/>
      </group> <!-- repository -->
      <group name="inventory">
        <method signature="InventoryServiceTest.testAddStockSuccess()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" name="testAddStockSuccess" class="com.company.scm.service.InventoryServiceTest"/>
        <method signature="InventoryServiceTest.testAddStock_ZeroQuantity_ThrowsException()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" name="testAddStock_ZeroQuantity_ThrowsException" class="com.company.scm.service.InventoryServiceTest"/>
        <method signature="InventoryServiceTest.testRemoveStockExceedingQuantity_ThrowsException()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" name="testRemoveStockExceedingQuantity_ThrowsException" class="com.company.scm.service.InventoryServiceTest"/>
        <method signature="InventoryServiceTest.testRemoveStockSuccess()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" name="testRemoveStockSuccess" class="com.company.scm.service.InventoryServiceTest"/>
        <method signature="InventoryServiceTest.testStockTransferUpdatesBothWarehouses(int,int,int)[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" name="testStockTransferUpdatesBothWarehouses" class="com.company.scm.service.InventoryServiceTest"/>
        <method signature="InventoryServiceTest.testTransferStock_InvalidDestination_ThrowsException()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" name="testTransferStock_InvalidDestination_ThrowsException" class="com.company.scm.service.InventoryServiceTest"/>
      </group> <!-- inventory -->
    </groups>
    <test started-at="2025-09-30T20:33:43 IST" name="Surefire test" finished-at="2025-09-30T20:33:44 IST" duration-ms="802">
      <class name="com.company.scm.service.ReportServiceTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testPrintInventoryReport()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" started-at="2025-09-30T20:33:44 IST" name="testPrintInventoryReport" finished-at="2025-09-30T20:33:44 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.company.scm.service.ReportServiceTest.testPrintInventoryReport(ReportServiceTest.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrintInventoryReport -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testPrintLowStockReport()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" started-at="2025-09-30T20:33:44 IST" name="testPrintLowStockReport" finished-at="2025-09-30T20:33:44 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.company.scm.service.ReportServiceTest.testPrintLowStockReport(ReportServiceTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrintLowStockReport -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.ReportServiceTest@62e136d3]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- com.company.scm.service.ReportServiceTest -->
      <class name="com.company.scm.service.OrderServiceTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.OrderServiceTest@18a70f16]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testFulfillSalesOrder_Success()[pri:1, instance:com.company.scm.service.OrderServiceTest@18a70f16]" started-at="2025-09-30T20:33:44 IST" name="testFulfillSalesOrder_Success" finished-at="2025-09-30T20:33:44 IST" duration-ms="3" status="FAIL">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[Inventory item for product P001 in warehouse W001 not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.
at com.company.scm.service.InventoryService.removeStock(InventoryService.java:62)
at com.company.scm.service.OrderService.fulfillSalesOrder(OrderService.java:70)
at com.company.scm.service.OrderServiceTest.testFulfillSalesOrder_Success(OrderServiceTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFulfillSalesOrder_Success -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.OrderServiceTest@18a70f16]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method signature="testFulfillSalesOrder_InsufficientStock_ThrowsException()[pri:2, instance:com.company.scm.service.OrderServiceTest@18a70f16]" started-at="2025-09-30T20:33:44 IST" name="testFulfillSalesOrder_InsufficientStock_ThrowsException" finished-at="2025-09-30T20:33:44 IST" duration-ms="2" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception of type class com.company.scm.exception.InsufficientStockException but got com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception of type class com.company.scm.exception.InsufficientStockException but got com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:739)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: com.company.scm.exception.EntityNotFoundException: Inventory item for product P001 in warehouse W001 not found.
at com.company.scm.service.InventoryService.removeStock(InventoryService.java:62)
at com.company.scm.service.OrderService.fulfillSalesOrder(OrderService.java:70)
at com.company.scm.service.OrderServiceTest.testFulfillSalesOrder_InsufficientStock_ThrowsException(OrderServiceTest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFulfillSalesOrder_InsufficientStock_ThrowsException -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.OrderServiceTest@18a70f16]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.OrderServiceTest@18a70f16]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- com.company.scm.service.OrderServiceTest -->
      <class name="com.company.scm.repository.ProductRepositoryTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:43 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testFindAll()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="testFindAll" finished-at="2025-09-30T20:33:44 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindAll -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testFindById_NotFound()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="testFindById_NotFound" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindById_NotFound -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method signature="testFindById_Success()[pri:0, instance:com.company.scm.repository.ProductRepositoryTest@15d9bc04]" started-at="2025-09-30T20:33:44 IST" name="testFindById_Success" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindById_Success -->
      </class> <!-- com.company.scm.repository.ProductRepositoryTest -->
      <class name="com.company.scm.service.InventoryServiceTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="2025-09-30T20:33:44 IST" duration-ms="3" status="FAIL">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testAddStockSuccess()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testAddStockSuccess" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddStockSuccess -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624077" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method signature="testAddStock_ZeroQuantity_ThrowsException()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testAddStock_ZeroQuantity_ThrowsException" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddStock_ZeroQuantity_ThrowsException -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624077" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testRemoveStockExceedingQuantity_ThrowsException()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testRemoveStockExceedingQuantity_ThrowsException" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRemoveStockExceedingQuantity_ThrowsException -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624078" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624078" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method signature="testRemoveStockSuccess()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testRemoveStockSuccess" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRemoveStockSuccess -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624079" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624079" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624079" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624082" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624083" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624083" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method signature="testStockTransferUpdatesBothWarehouses(int,int,int)[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testStockTransferUpdatesBothWarehouses" data-provider="transferData" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStockTransferUpdatesBothWarehouses -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624083" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testStockTransferUpdatesBothWarehouses(int,int,int)[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testStockTransferUpdatesBothWarehouses" data-provider="transferData" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStockTransferUpdatesBothWarehouses -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624084" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624084" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testStockTransferUpdatesBothWarehouses(int,int,int)[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testStockTransferUpdatesBothWarehouses" data-provider="transferData" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStockTransferUpdatesBothWarehouses -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="setup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624085" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="cleanup" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1759244624085" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method signature="testTransferStock_InvalidDestination_ThrowsException()[pri:0, instance:com.company.scm.service.InventoryServiceTest@51b7e5df]" started-at="2025-09-30T20:33:44 IST" name="testTransferStock_InvalidDestination_ThrowsException" finished-at="2025-09-30T20:33:44 IST" duration-ms="0" status="SKIP">
          <exception class="com.company.scm.exception.EntityNotFoundException">
            <message>
              <![CDATA[W001]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.company.scm.exception.EntityNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransferStock_InvalidDestination_ThrowsException -->
      </class> <!-- com.company.scm.service.InventoryServiceTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
