<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="3b7b2133aad05b1" failures="0" tests="9" name="com.company.scm.service.InventoryServiceTest" time="0.003" errors="1" timestamp="2025-09-30T20:33:44 IST" skipped="8">
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testTransferStock_InvalidDestination_ThrowsException" time="0.000">
    <skipped/>
  </testcase> <!-- testTransferStock_InvalidDestination_ThrowsException -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testAddStockSuccess" time="0.000">
    <skipped/>
  </testcase> <!-- testAddStockSuccess -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testRemoveStockSuccess" time="0.000">
    <skipped/>
  </testcase> <!-- testRemoveStockSuccess -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testAddStock_ZeroQuantity_ThrowsException" time="0.000">
    <skipped/>
  </testcase> <!-- testAddStock_ZeroQuantity_ThrowsException -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testRemoveStockExceedingQuantity_ThrowsException" time="0.000">
    <skipped/>
  </testcase> <!-- testRemoveStockExceedingQuantity_ThrowsException -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testStockTransferUpdatesBothWarehouses" time="0.000">
    <skipped/>
  </testcase> <!-- testStockTransferUpdatesBothWarehouses -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testStockTransferUpdatesBothWarehouses" time="0.000">
    <skipped/>
  </testcase> <!-- testStockTransferUpdatesBothWarehouses -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="setup" time="0.003">
    <error message="W001" type="com.company.scm.exception.EntityNotFoundException">
      <![CDATA[com.company.scm.exception.EntityNotFoundException: W001
at com.company.scm.service.InventoryService.addStock(InventoryService.java:35)
at com.company.scm.service.InventoryServiceTest.setup(InventoryServiceTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase classname="com.company.scm.service.InventoryServiceTest" name="testStockTransferUpdatesBothWarehouses" time="0.000">
    <skipped/>
  </testcase> <!-- testStockTransferUpdatesBothWarehouses -->
  <system-out/>
</testsuite> <!-- com.company.scm.service.InventoryServiceTest -->
